"""
Export AmiGo patterns to CrochetPARADE format.

CrochetPARADE (https://www.crochetparade.org) is a pattern programming
language that can visualise and simulate crochet in 3-D.

Built-in stitch notation used here (no DEF: lines needed):
  ring           magic ring foundation
  sc             single crochet
  scNinc         N sc into the same base stitch (increase; sc2inc = standard inc)
  scNtog         sc2tog-style decrease over N base stitches
  Nsc            run of N single crochets  (also: N*sc or "N sc")
  Nsc2inc        run of N standard increases
  k*[sc,sc2inc]  repeat sequence k times

Amigurumi is worked in continuous rounds — no 'turn' commands are emitted.
Each row in the AmiGo output becomes one round (line) in the .cp file.
"""

from __future__ import annotations
from .instructions import Stitch
from .loop_folding import _fold_runs, _find_period


# ---------------------------------------------------------------------------
# Per-stitch translation
# ---------------------------------------------------------------------------

def _stitch_cp(s: Stitch) -> str:
    """Translate a single Stitch to its CrochetPARADE token."""
    if s.type == "sc":
        return "sc"
    if s.type == "inc":
        return f"sc{s.x}inc"   # sc2inc, sc3inc, sc6inc, …
    if s.type == "dec":
        return f"sc{s.x}tog"   # sc2tog, sc3tog, sc6tog, …
    return s.type


# ---------------------------------------------------------------------------
# Run-length helper that works on CrochetPARADE tokens
# ---------------------------------------------------------------------------

def _cp_runs(stitches: list[Stitch]) -> list[tuple[int, Stitch]]:
    """Collapse adjacent identical stitches into (count, Stitch) pairs."""
    return _fold_runs(stitches)


def _run_to_cp(count: int, s: Stitch) -> str:
    """Format a run as a CrochetPARADE token."""
    tok = _stitch_cp(s)
    if count == 1:
        return tok
    # e.g. 5sc, 3sc2inc, 4sc2tog
    return f"{count}{tok}"


# ---------------------------------------------------------------------------
# Row → CrochetPARADE line
# ---------------------------------------------------------------------------

def _row_to_cp(stitches: list[Stitch]) -> str | None:
    """
    Convert one row's Stitch list to a CrochetPARADE line.

    Returns None for the magic row (handled as 'ring' on its own line).
    """
    if not stitches:
        return ""

    if len(stitches) == 1 and stitches[0].type == "magic":
        return None  # caller emits 'ring' for this row

    # Try whole-row period (e.g. 6 × [sc, sc2inc] → 6*[sc,sc2inc])
    p = _find_period(stitches)
    if p is not None and p < len(stitches):
        reps = len(stitches) // p
        unit = stitches[:p]
        if p == 1:
            return f"{reps}{_stitch_cp(unit[0])}"
        unit_str = ",".join(_stitch_cp(s) for s in unit)
        return f"{reps}*[{unit_str}]"

    # Run-length encode
    parts = [_run_to_cp(c, s) for c, s in _cp_runs(stitches)]
    return ",".join(parts)


# ---------------------------------------------------------------------------
# Full pattern export
# ---------------------------------------------------------------------------

_HEADER = """\
# Generated by AmiGo
# Paste into https://www.crochetparade.org to visualise in 3-D
"""


def to_crochetparade(all_instructions: list[list[Stitch]]) -> str:
    """
    Convert the full AmiGo instruction list to a CrochetPARADE pattern string.

    Parameters
    ----------
    all_instructions : list returned by generate_all_instructions()

    Returns
    -------
    cp_text : str — ready to paste into https://www.crochetparade.org
    """
    lines = [_HEADER]

    for row_idx, stitches in enumerate(all_instructions, start=1):
        cp_line = _row_to_cp(stitches)

        if cp_line is None:
            # Magic ring row → emit 'ring'; the NEXT row's scNinc puts N
            # stitches into it, so no extra line needed here.
            lines.append(f"# Row {row_idx}: magic ring")
            lines.append("ring")
        elif cp_line:
            lines.append(f"# Row {row_idx}")
            lines.append(cp_line)

    return "\n".join(lines) + "\n"
